---
- name: debian | Adding Microsoft repo key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Adding MSSQL tools repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/{{ ansible_distribution|lower }}/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Adding MSSQL repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/{{ ansible_distribution|lower }}/{{ ansible_distribution_version }}/mssql-server-2017 {{ ansible_distribution_release }} main
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Installing MSSQL
  apt:
    name: ["mssql-server"]
    state: present
  environment:
    ACCEPT_EULA: "y"
  become: true
  register: result
  until: result is successful

- name: debian | Installing MSSQL Tools
  apt:
    name: ["mssql-tools"]
    state: present
  environment:
    ACCEPT_EULA: "y"
  become: true
  register: result
  until: result is successful
